[FileDialog]
history=file:///home/jake/Downloads/It.Was.Just.an.Accident.2025.1080p.ENG.SUB.SCREENER.WEB-DL.H264.AAC-AOC, file:///home/jake/Downloads/Tron Ares (2025) [1080p] [WEBRip] [5.1] [YTS.LT], file:///home/jake/Downloads, file:///home/jake/Documents/FlashPrint, file:///run/media/jake/026C-293F, file:///home/jake/Downloads/Mutiny (2026) [1080p] [WEBRip] [5.1] [YTS.GG - YTS.BZ]
lastVisited=file:///home/jake/Downloads/Mutiny (2026) [1080p] [WEBRip] [5.1] [YTS.GG - YTS.BZ]
qtVersion=5.15.19
shortcuts=file:///home/jake/Desktop, file:///home/jake/Documents, file:///home/jake/Downloads, file:///home/jake, file:///home/jake/Pictures, file:///home/jake/Documents/3D/Yash_Kickstand
sidebarWidth=99
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2r\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1'\0\0\0\x1\0\0\0\0\0\0\0j\0\0\0\x1\0\0\0\0\0\0\0\x45\0\0\0\x1\0\0\0\0\0\0\0\x9c\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
